kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flow-crm
  namespace: ralvarez
spec:
  to:
    kind: Service
    name: flow-crm
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
    destinationCACertificate: ''
  port:
    targetPort: 8080-tcp
